#**SVD**

#import libraries

In [ ]:
import numpy as np


#Load the tabular dataset :



In [ ]:
dataset = np.array
  [: , :K]
  [:, :2]
   ([
    [2, 1, 0, 4],
    [3, 4, 0, 2],
    [1, 1, 0, 5],
    [0, 2, 5, 0],
    [4, 0, 1, 2]
])


#Perform Singular Value Decomposition (SVD)


In [ ]:
# Perform Singular Value Decomposition (SVD) on the dataset
U, s, VT = np.linalg.svd(dataset)
# U: left singular vectors (m x m matrix where m is the number of rows in the dataset)
# s: singular values (1D array of singular values)
# VT: right singular vectors transposed (n x n matrix where n is the number of columns in the dataset)



# Extract the singular values and vectors

In [ ]:
# Convert the singular values array into a diagonal matrix
singular_values = np.diag(s)
# singular_values: a diagonal matrix with singular values on the diagonal
# The shape of singular_values will be (m, n) where m is the number of rows and n is the number of columns in the dataset


# Assign the left singular vectors to a variable for clarity
left_singular_vectors = U

# Assign the right singular vectors to a variable for clarity، # VT.T is the transpose of VT to get the original V matrix
right_singular_vectors = VT.T


# Perform dimensionality reduction by selecting top k singular values and vectors


In [ ]:
k = 2 # Setting k = 2 means we are reducing the dimensionality to 2, keeping the top 2 singular values and corresponding singular vectors.

reduced_dataset = np.dot(np.dot(left_singular_vectors[:, :k], singular_values[:k, :k]), right_singular_vectors[:, :k].T)
# reduced_dataset: The dataset reconstructed using only the top k singular values and corresponding singular vectors.

# np.dot: Performs matrix multiplication.
# left_singular_vectors[:, :k]: Selects the first k columns of the left singular vectors matrix (U).
# singular_values[:k, :k]: Selects the top k x k block from the diagonal matrix of singular values (Σ).
# right_singular_vectors[:, :k].T: Selects the first k columns of the right singular vectors matrix (V) and then transposes it.

# The multiplication order is important here:
# 1. np.dot(left_singular_vectors[:, :k], singular_values[:k, :k]): Multiplies the reduced U matrix with the reduced Σ matrix.
# 2. np.dot(..., right_singular_vectors[:, :k].T): Multiplies the result with the transposed reduced V matrix.
# This effectively reconstructs the original dataset using only the top k singular values and vectors.


# Print the original and reduced datasets


In [ ]:
print("Original Dataset:")
print(dataset)
print("\nReduced Dataset:")
print(reduced_dataset)


Original Dataset:
[[2 1 0 4]
 [3 4 0 2]
 [1 1 0 5]
 [0 2 5 0]
 [4 0 1 2]]

Reduced Dataset:
[[ 2.42783083  1.34469234 -0.28088786  3.55528003]
 [ 2.48095375  2.03039214  1.21169626  3.19513057]
 [ 2.54437376  1.32108273 -0.49569821  3.78477327]
 [ 0.56412157  2.38529993  4.66847769 -0.55714942]
 [ 2.03649155  1.48065473  0.56987114  2.74683942]]


#**Well done :)**