#**SVD**

#import libraries

In [1]:
import numpy as np


#Load the tabular dataset :



In [2]:
dataset = np.array([
    [2, 1, 0, 4],
    [3, 4, 0, 2],
    [1, 1, 0, 5],
    [0, 2, 5, 0],
    [4, 0, 1, 2]
])
# raw , column
# ( 5 x 4 )
# (m , n)


#Perform Singular Value Decomposition (SVD)


In [8]:
U, s, VT = np.linalg.svd(dataset)

#U: Left singular vectors
#s:  singular calues
#VT: Right singular vector transposed ( n x n matrix)
s

array([8.85464509, 5.39288909, 3.32855123, 2.9039205 ])

# Extract the singular values and vectors

In [9]:
singular_values = np.diag(s)
left_singular_vectors = U
right_singular_vectors = VT.T
singular_values

array([[8.85464509, 0.        , 0.        , 0.        ],
       [0.        , 5.39288909, 0.        , 0.        ],
       [0.        , 0.        , 3.32855123, 0.        ],
       [0.        , 0.        , 0.        , 2.9039205 ]])

# Perform dimensionality reduction by selecting top k singular values and vectors


In [5]:
k = 2
reduced_dataset = np.dot(np.dot(left_singular_vectors[:, :k], singular_values[:k, :k]), right_singular_vectors[:, :k].T)


# Print the original and reduced datasets


In [6]:
print("Original Dataset:")
print(dataset)
print("\nReduced Dataset:")
print(reduced_dataset)


Original Dataset:
[[2 1 0 4]
 [3 4 0 2]
 [1 1 0 5]
 [0 2 5 0]
 [4 0 1 2]]

Reduced Dataset:
[[ 2.42783083  1.34469234 -0.28088786  3.55528003]
 [ 2.48095375  2.03039214  1.21169626  3.19513057]
 [ 2.54437376  1.32108273 -0.49569821  3.78477327]
 [ 0.56412157  2.38529993  4.66847769 -0.55714942]
 [ 2.03649155  1.48065473  0.56987114  2.74683942]]


#**Well done :)**